services:
  - type: web
    name: nova-shopify-app
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SHOPIFY_PIXEL_ACCOUNT_ID
        value: "nova-pixel"
      - key: DATABASE_URL
        fromDatabase:
          name: nova-db
          property: connectionString
    buildFilter:
      paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.json"
      - "**/*.prisma"
      - "prisma/**"

databases:
  - name: nova-db
    plan: starter 