name = "web-pixel"
type = "web_pixel_extension"

network_access = true
runtime_context = "strict"

description = "Tracks visitor behavior via Web Pixel and sends events to your analytics endpoint."

[customer_privacy]
analytics = true
marketing = true
preferences = false
sale_of_data = "enabled"

[settings]
type = "object"

[settings.fields.accountID]
name = "Account ID"
description = "Your internal tracking or analytics account ID"
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" },
  { name = "max", value = "1000000" }
]
