# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af0837af52a3ec00869d94fe5c0d74d5"
name = "nova"
handle = "nova-6"
application_url = "https://nova-ebgc.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_orders,write_products,read_customers,read_orders,read_products,write_script_tags,write_pixels,read_customer_events,read_pixels"

[auth]
redirect_urls = [
  "https://nova-ebgc.onrender.com/auth/callback",
  "https://nova-ebgc.onrender.com/auth/shopify/callback",
  "https://nova-ebgc.onrender.com/api/auth/callback"
]

[pos]
embedded = false
